"""Initial migration

Revision ID: 1c940b1b3a76
Revises: 
Create Date: 2025-09-09 12:01:47.719944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c940b1b3a76'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profile',
    sa.Column('uid', sa.String(length=128), nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('favorite_color', sa.Enum('RED', 'BLUE', 'YELLOW', 'GRAY', 'WHITE', 'BLACK', name='favoritecolor', native_enum=False), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profile')
    # ### end Alembic commands ###
